- name: Install and configure Docker for insecure registry
  hosts: controller
  become: yes
  vars:
    ansible_user: "{{ pi_user }}"
  tasks:
  - name: Install Docker 
    shell: 'curl -sSL https://get.docker.com | sh'
  
  - name: adding existing user '{{ pi_user }}' to docker group 
    user:
      name: '{{ pi_user }}'
      groups: docker
      append: yes

  - name: Configure for insecure local registry
    become: yes
    copy:
      content: '{ "insecure-registries" : ["{{ docker_registry_host }}"] }'
      dest: "/etc/docker/daemon.json"
      owner: "root"
      group: "root"
      mode: 0644
  
  - name: Restart the docker service
    become: yes
    service:
      name: docker
      state: restarted  

  - name: Create registry directory
    file:
      path: /docker_registry
      state: directory
      mode: '0755'

  - name: Install pip
    apt:
      name: python-pip
      state: present

  - name: Install docker python package for ansible
    pip:
      name: docker

  - name: Run registry container
    docker_container:
      name: registry
      image: registry:2
      detach: yes
      restart: yes
      restart_policy: always
      volumes:
        - /docker_registry:/var/lib/registry
      ports:
        - "5000:5000"
 

            
         