- hosts: kube_master
  become: yes
  tasks:
  - name: Install K3s in master
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"

  - name: Read node-token from master
    slurp:
      src: /var/lib/rancher/k3s/server/node-token
    register: K3S_TOKEN

  - name: "Add K3S Token to dummy host"
    add_host:
      name:   "K3S_TOKEN_HOLDER"
      token:  "{{ K3S_TOKEN.content | b64decode | regex_replace('\n', '') }}"


- hosts: kube_workers
  become: yes
  tasks:
  - name: Install K3s in workers
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"
      K3S_URL: "https://10.10.1.100:6443"
      K3S_TOKEN: "{{ hostvars['K3S_TOKEN_HOLDER']['token'] }}"