- hosts: kube_master
  become: yes
  tasks:
  - name: Install K3s in master
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"

  - name: Read node-token from master
    slurp:
      src: /var/lib/rancher/k3s/server/node-token
    register: K3S_TOKEN

  - name: "Add K3S Token to dummy host"
    add_host:
      name:   "K3S_TOKEN_HOLDER"
      token:  "{{ K3S_TOKEN.content | b64decode | regex_replace('\n', '') }}"


- hosts: kube_workers
  become: yes
  tasks:
  - name: Install K3s in workers
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"
      K3S_URL: "https://10.10.1.100:6443"
      K3S_TOKEN: "{{ hostvars['K3S_TOKEN_HOLDER']['token'] }}"

- hosts: controller
  become: yes
  tasks:
  - name: Install K3s command tools on controller
    shell: 'curl -sfL https://get.k3s.io | sh -'
    environment:
      K3S_KUBECONFIG_MODE: "644"
      INSTALL_K3S_SKIP_ENABLE: "true"

  - name: Install HELM on controller
    shell: 'curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash'

- name: point kube nodes to local insecure docker registry
  hosts: kube_master:kube_workers
  become: yes
  tasks:
  - name: Create k3s directory if it does't exist
    file:
      path: /etc/rancher/k3s/
      state: directory
      mode: '0755'
            
  - name: Configure for insecure local docker registry
    copy:
        content: |
          mirrors:
            segsfault.com:
              endpoint:
                - "http://{{ docker_registry_host }}"
        dest: "/etc/rancher/k3s/registries.yaml"
        owner: "root"
        group: "root"
        mode: 0644