kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: grafana-server
  ports:
    - name: grafanaui
      port: 3000
      targetPort: 3000
      nodePort: 30000