apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-pvc
    namespace: monitoring    
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""      
  resources:
    requests:
      storage: 1Gi       