apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    usage: monitoring
  namespace: monitoring 
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany 
  nfs: 
    path: /mnt/homelab 
    server: control.segsfault.com 
    readOnly: false