# This gets installed in the nfs drive at: k3s/prometheus/prometheus.yml
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 60 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['10.10.1.10:9100']
    - targets: ['10.10.1.100:9100']
    - targets: ['10.10.1.101:9100']
    - targets: ['10.10.1.102:9100']
    - targets: ['10.10.1.103:9100']
    - targets: ['10.10.1.104:9100']