# Update packages and install some common packages
- name: apt-get update
  become: yes
  apt:
    update_cache: yes

- name: apt-get dist-upgrade
  become: yes
  apt:
    upgrade: dist

- name: Install some needed packages
  become: yes
  package:
    name: 
      - supervisor
      - nfs-common
      - rpcbind
    state: present

- name: Install Docker everywhere
  shell: 'curl -sSL https://get.docker.com | sh'

- name: adding existing user '{{ pi_user }}' to docker group 
  user:
    name: '{{ pi_user }}'
    groups: docker
    append: yes  